
export enum EventKeys {
  DIRTY_ITEMS_UPDATED="DIRTY_ITEMS_UPDATED",
  ENTITY_UPDATED="ENTITY_UPDATED",
  Empty="Empty",
  ENTITY_CREATED="ENTITY_CREATED",
  EditEntity="EditEntity",
  NewVirtual="NewVirtual",
  NewEntity="NewEntity",
  UPDATE_REPORTABLE_ENTITY_DISPLAY_NAME="updateReportableEntityDisplayName",
  AFTER_ENTITIES_LOADED="AFTER_ENTITIES_LOADED",
  Entities="Entities",
  ENTITY_UPDATE_CANCELED="ENTITY_UPDATE_CANCELED",
  ENABLE_GLOBAL_SAVE="ENABLE_GLOBAL_SAVE",
  DISABLE_GLOBAL_SAVE="DISABLE_GLOBAL_SAVE",
  UPLOAD_DATA="UPLOAD_DATA",
  SET_APP_BUSY="SET_APP_BUSY",
  ENTITY_EDITING="ENTITY_EDITING",
  EDITING_AUTH="EDITING_AUTH"
 
}
